name: tracker_sim
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310h540bb41_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - intel-openmp=2025.0.0=haa95532_1164
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py310h0b37514_0
  - mkl_fft=2.1.1=py310h300f80d_0
  - mkl_random=1.3.0=py310ha5e6156_0
  - numexpr=2.14.1=py310h7660c64_0
  - numpy=2.2.5=py310h7894be3_2
  - numpy-base=2.2.5=py310h7794460_2
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py310haa95532_1
  - pandas=2.3.3=py310h42c1672_1
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - pytz=2025.2=py310haa95532_0
  - setuptools=80.10.1=py310haa95532_0
  - six=1.17.0=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - awscrt==0.31.1
      - awsiotsdk==1.28.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - customtkinter==5.2.2
      - darkdetect==0.8.0
      - decorator==5.2.1
      - future==1.0.0
      - geocoder==1.38.1
      - idna==3.11
      - pillow==12.1.0
      - pyperclip==1.11.0
      - pywin32==311
      - ratelim==0.1.6
      - requests==2.32.5
      - tkintermapview==1.29
      - urllib3==2.6.3

